version: '3'
services:

  backend:
    build: ../pythonSite/Site
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build: ../smsSite_frontend
    container_name: frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx:ro
    depends_on:
      - backend
      - frontend


