version: '3'
services:

  backend:
    build: ../pythonSite/Site/smsSite
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build: ../smsSite_frontend
    container_name: frontend
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend


