version: '3'
services:

  db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=o2Juwcjsnx
      - POSTGRES_DB=smsProject
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - postgres_data:/data/postgres


  backend:
    build: ../pythonSite/Site/smsSite
    command: sh entrypoint.sh
    container_name: backend
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"

  frontend:
    build: ../smsSite_frontend
    container_name: frontend
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
    driver: local


