version: '3'
services:

  backend:
    build: ../pythonSite/Site
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build: ../smsSite_frontend
    container_name: frontend
    ports:
      - "8001:8001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/api_gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend


