version: '3'
services:

  backend:
    build: ../pythonSite/Site
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  frontend:
    build: ../smsSite_frontend
    container_name: frontend
    ports:
      - "80:8080"

